[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; build options
build_flags =
    -std=c++17                   ; C++ standard
    -DCORE_DEBUG_LEVEL=3         ; debug level
    -DARDUINOJSON_ENABLE_ARDUINO_STRING=1                  
    -fexceptions                 ; enable exceptions
    -O2                          ; optimize for size and speed
    -Wall                        ; enable all warnings
    -Wextra
    -Wno-unused-variable
    -Wno-unused-parameter

; add include directories
build_src_flags =
    -I include
    -I AI_model
    -I cloud
    -I data
    -I src
    -I EAEAPI

; libraries
lib_deps =
    adafruit/DHT sensor library @ ^1.4.4
    bblanchon/ArduinoJson @ ^6.19.4

; upload and monitor speeds
upload_speed = 921600
monitor_speed = 115200

; filesystem
board_build.filesystem = spiffs

; stack size
board_build.stack_size = 16384

; serial monitor filters
monitor_filters =
    esp32_exception_decoder
    time
    default